service: serverless-chat

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"

functions:
  auth:
    handler: com.serverless.Handler
    events:
      - http:
          path: iot/keys
          method: get
          cors: true
    timeout: 10

package:
  artifact: target/serverless-chat.jar